data:
  input_csv: "Loan_data.csv"
  status_column: "loan_status"
  target_column: "flg_target"
  allowed_status:
    good:
      - "Fully Paid"
      - "Does not meet the credit policy. Status: Fully Paid"
    bad:
      - "Charged Off"
      - "Default"
      - "Late (31-120 days)"
      - "Does not meet the credit policy. Status: Charged Off"
  drop_missing_status: true
  output_dir: "."
  output_pca_lda_csv: "df_pca_lda.csv"
  output_anova_csv: "df_anova.csv"

cleaning:
  enable_drop_null_columns: true
  drop_null_threshold: 0.95
  enable_drop_irrelevant_columns: true
  drop_columns:
    - "Unnamed: 0"
    - "Unnamed: 0.1"
    - member_id
    - url
    - desc
    - disbursement_method
    - payment_plan_start_date
    - verification_status
    - addr_state
    - zip_code
    - policy_code
    - application_type
  enable_drop_ex_post: true
  drop_ex_post_columns:
    - out_prncp
    - out_prncp_inv
    - total_pymnt_inv
    - total_pymnt
    - total_rec_int
    - total_rec_late_fee
    - recoveries
    - collection_recovery_fee
    - last_pymnt_d
    - last_credit_pull_d
    - recovery_ratio
    - total_rec_prncp
    - last_pymnt_amnt
    - last_fico_range_low
    - last_fico_range_high

features:
  derive:
    enable_term_integer: true
    enable_emp_length_months: true
    enable_ratio_loan_income: true
    enable_installment_pct_loan: true
    enable_fico_avg: true
    enable_revol_util_ratio: true

selection:
  filter_missing:
    enable: true
    threshold: 0.5
    rescue_by_correlation: true
    min_corr: 0.1
    min_samples: 30
  filter_cv:
    enable: true
    threshold: 0.1
    rescue_by_correlation: true
    min_corr: 0.1
    min_samples: 30
  pca:
    enable: true
    n_components: 35
    plot_variance: false
  lda_importance:
    enable: true
    importance_threshold: 0.05
    plot_importance: false
  anova:
    enable: true
    min_f_score: null
    max_p_value: 0.05
    top_n: null
  correlation_redundancy:
    enable: true
    threshold: 0.6
    plot_heatmap: false

# Configuración para separación inteligente de variables
separation:
  max_unique_categorical: 20          # Máximo valores únicos para mantener categórica
  max_concentration_categorical: 0.98 # Máxima concentración de un solo valor (98%)
  enable_auto_numeric_conversion: true # Habilitar conversión automática a numérico
  enable_categorical_filtering: true   # Habilitar filtrado de categóricas problemáticas

# Configuración para selección de variables categóricas
categorical_selection:
  enable_chi_square: true             # Habilitar test Chi-square
  enable_woe_iv: true                 # Habilitar cálculo WOE/IV
  iv_threshold: 0.1                  # Umbral mínimo de Information Value
  chi_square_threshold: 0.05         # Umbral p-value para Chi-square

# Configuración para protección de int_rate
int_rate_protection:
  enable_protection: true             # Habilitar protección de int_rate
  protected_variable: "int_rate"     # Variable a proteger
  correlation_threshold: 0.7         # Umbral de correlación alta con int_rate
  priority_over_correlated: true     # Priorizar int_rate sobre variables correlacionadas
  force_include_int_rate: true       # Forzar inclusión de int_rate en resultados finales

logging:
  verbose: true

