# Configuration for modeling pipeline (train/test, sensitivity, and smart grids)

# Control de modelos a ejecutar
models:
  enable_logit: true           # Regresión logística
  enable_gnb: true            # Gaussian Naive Bayes
  enable_svm_linear: true     # SVM Lineal
  enable_svm_linear_smart: true  # SVM Lineal con búsqueda
  enable_svm_rbf_smart: false    # SVM RBF (no ejecutar)
  enable_mlp: true            # Red Neuronal MLP

# Control de ejecución de etapas
execution:
  run_training: true
  run_plots: false
  run_comparator: true

# Configuración de datos
data:
  test_size: 0.30
  random_seed: 42

# Configuración de sensibilidad
sensitivity:
  max_rows: 50000

# Configuración de análisis de sensibilidad
sensitivity_analysis:
  enable_real_sensitivity: true
  step: 2.0
  min_samples: 100
  confidence_level: 0.95

# Configuración LOGIT
logit:
  max_iter: 1000
  random_state: 42

# Configuración GNB
gnb:
  var_smoothing: 0.000000001  # 1e-9 como float
  search_grid: [-12, -6, 20]  # logspace(-12, -6, 20)

# Configuración SVM Lineal
svm_linear:
  max_train_samples: null     # Sin límite - usar todo el dataset
  max_test_samples: null      # Sin límite - usar todo el dataset
  tol: 0.001
  max_iter: 3000
  random_state: 42

# Configuración SVM Lineal Smart Search
svm_linear_smart:
  max_train_samples: null     # Sin límite - usar todo el dataset
  max_test_samples: null      # Sin límite - usar todo el dataset
  tol: 0.001
  max_iter: 3000
  random_state: 42
  search_space:
    C: [-2, 2, 5]             # logspace(-2, 2, 5)
    loss: ['squared_hinge']

# Configuración SVM RBF
svm_rbf:
  max_train_samples: null     # Sin límite - usar todo el dataset
  max_test_samples: null      # Sin límite - usar todo el dataset
  tol: 0.001
  max_iter: 2000
  cache_size: 500
  random_state: 42

# Configuración MLP
mlp:
  max_train_samples: null     # Sin límite - usar todo el dataset
  max_test_samples: null      # Sin límite - usar todo el dataset
  max_iter: 50
  n_iter_no_change: 5
  random_state: 42
  hidden_layer_sizes: [64, 32]
  activation: 'relu'
  solver: 'adam'
  alpha: 0.0001
  batch_size: 'auto'
  learning_rate: 'adaptive'
  early_stopping: true

# Configuración de logging
logging:
  enable_file_logging: true
  log_filename: "log_MODELING.txt"
  enable_progress_bar: true
