data:
  input_csv: "Loan_data.csv"
  status_column: "loan_status"
  target_column: "flg_target"
  allowed_status:
    good:
      - "Fully Paid"
      - "Does not meet the credit policy. Status: Fully Paid"
    bad:
      - "Charged Off"
      - "Default"
      - "Late (31-120 days)"
      - "Does not meet the credit policy. Status: Charged Off"
  drop_missing_status: true
  output_dir: "."
  output_pca_lda_csv: "df_pca_lda.csv"
  output_anova_csv: "df_anova.csv"

cleaning:
  enable_drop_null_columns: true
  enable_drop_irrelevant_columns: true
  drop_columns:
    - "Unnamed: 0"
    - "Unnamed: 0.1"
    - member_id
    - url
    - desc
    - disbursement_method
    - payment_plan_start_date
    - verification_status
    - addr_state
    - zip_code
    - policy_code
    - application_type
  enable_drop_ex_post: true
  drop_ex_post_columns:
    - out_prncp
    - out_prncp_inv
    - total_pymnt_inv
    - total_pymnt
    - total_rec_int
    - total_rec_late_fee
    - recoveries
    - collection_recovery_fee
    - last_pymnt_d
    - last_credit_pull_d
    - recovery_ratio
    - total_rec_prncp
    - last_pymnt_amnt
    - last_fico_range_low
    - last_fico_range_high

features:
  derive:
    # Variables básicas existentes
    enable_term_integer: true
    enable_emp_length_months: true
    enable_ratio_loan_income: true
    enable_installment_pct_loan: true
    enable_fico_avg: true
    enable_revol_util_ratio: true
    enable_installment_income_ratio: true
    
    # NUEVAS VARIABLES PARA MEJORAR AUC (TEMPORALMENTE DESHABILITADAS PARA DEBUG)
    # 1. Variables de capacidad de pago
    enable_debt_to_income_enhanced: true
    enable_payment_capacity_score: true
    
    # 2. Variables de historial crediticio
    enable_credit_history_score: true
    enable_credit_utilization_risk: true
    
    # 3. Variables de comportamiento financiero
    enable_financial_behavior_score: true
    enable_credit_seeking_behavior: true
    
    # 4. Variables de estabilidad
    enable_employment_stability: true
    enable_loan_risk_profile: true
    
    # 5. Variables de interacción
    enable_fico_dti_interaction: true
    enable_income_grade_interaction: true
    
    # 6. Variables de ratios financieros avanzados
    enable_advanced_financial_ratios: true
    
    # 7. Variables de tendencias temporales
    enable_temporal_trends: true

# Configuración para preprocesamiento de variables numéricas
preprocessing:
  enable_missing_imputation: true        # Habilitar imputación de valores faltantes
  imputation_strategy: "median"          # Estrategia: "median", "mean", "mode"
  enable_winsorization: true             # Habilitar winsorización (topeo) de outliers
  winsorization_percentiles:             # Percentiles para topeo
    lower: 0.02                          # Percentil inferior (1%)
    upper: 0.98                          # Percentil superior (99%)

selection:
  filter_missing:
    enable: true
    threshold: 0.95
    rescue_by_correlation: true
    min_corr: 0.1
    min_samples: 30
  filter_cv:
    enable: true
    threshold: 0.05
    rescue_by_correlation: true
    min_corr: 0.1
    min_samples: 30
  pca:
    enable: true
    # Modo de selección de componentes PCA:
    # - "fixed_components": Usa un número fijo de componentes (n_components)
    # - "variance_percentage": Calcula automáticamente el número de componentes que explican el porcentaje especificado
    mode: "variance_percentage"  # Opciones: "fixed_components" o "variance_percentage"
    n_components: 35             # Solo se usa si mode="fixed_components"
    variance_threshold: 0.95     # Solo se usa si mode="variance_percentage" (95% de varianza)
    plot_variance: false
  lda_importance:
    enable: true
    importance_threshold: 0.03
    plot_importance: false
  anova:
    enable: true
    min_f_score: null
    max_p_value: 0.05
    top_n: null
  correlation_redundancy:
    enable: true
    threshold: 0.6
    plot_heatmap: false

# Configuración para separación inteligente de variables
separation:
  max_unique_categorical: 20          # Máximo valores únicos para mantener categórica
  max_concentration_categorical: 0.98 # Máxima concentración de un solo valor (98%)
  sample_size_for_analysis: 100       # Tamaño de muestra para análisis de tipos
  max_code_length: 10                 # Longitud máxima para considerar como código
  statistical_percentiles: [0.01, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99]  # Percentiles para estadísticas

# Configuración para selección de variables categóricas
categorical_selection:
  enable_chi_square: true             # Habilitar test Chi-square
  enable_woe_iv: true                 # Habilitar cálculo WOE/IV
  iv_threshold: 0.1                  # Umbral mínimo de Information Value (MEDIA en adelante)
  chi_square_threshold: 0.05         # Umbral p-value para Chi-square
  # Categorías de Information Value según estándares de la industria
  iv_categories:
    no_predictive: 0.02              # No predictiva
    weak: 0.1                        # Débil
    medium: 0.3                      # Media
    strong: 0.5                      # Fuerte

# Configuración para protección de int_rate
int_rate_protection:
  enable_protection: true            # Habilitar protección de int_rate
  protected_variable: "int_rate"     # Variable a proteger
  correlation_threshold: 0.7         # Umbral de correlación alta con int_rate

logging:
  verbose: true

