# Configuration for modeling pipeline (train/test, sensitivity, and smart grids)

data:
  test_size: 0.30
  random_seed: 42

sensitivity:
  max_rows: 50000

svm_linear:
  max_train_samples: 100000
  max_test_samples: 100000
  tol: 0.001
  max_iter: 3000

svm_rbf:
  max_train_samples: 50000
  max_test_samples: 100000
  tol: 0.001
  max_iter: 2000
  cache_size: 500

mlp:
  max_train_samples: 100000
  max_test_samples: 100000
  max_iter: 50
  n_iter_no_change: 5
